inherit_from: ../hitobito/.rubocop.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - Rakefile
    - Gemfile
    - db/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - spec/**/*
    - test/**/*
    - lib/jubla_ost/**/*
    - vendor/**/*
